<<<<<<< HEAD
# Generated by Django 4.1 on 2023-04-27 21:09
=======
# Generated by Django 4.2 on 2023-04-27 21:28
>>>>>>> 1182be5c3d078c91c8048dab1ab88dd55c76df74

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_doctor_doctor_id_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
<<<<<<< HEAD
            field=models.IntegerField(default=96729, editable=False, primary_key=True, serialize=False, unique=True),
=======
            field=models.IntegerField(default=46542, editable=False, primary_key=True, serialize=False, unique=True),
>>>>>>> 1182be5c3d078c91c8048dab1ab88dd55c76df74
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
<<<<<<< HEAD
            field=models.IntegerField(default=27302, editable=False, primary_key=True, serialize=False, unique=True),
=======
            field=models.IntegerField(default=40104, editable=False, primary_key=True, serialize=False, unique=True),
>>>>>>> 1182be5c3d078c91c8048dab1ab88dd55c76df74
        ),
    ]
